const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_AMOUNT_MIN: 'INVALID_AMOUNT_MIN',
  INVALID_AMOUNT_SCALE: 'INVALID_AMOUNT_SCALE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  WALLET_INSUFFICIENT_BALANCE: 'WALLET_INSUFFICIENT_BALANCE',
} as const

export { ERROR_CODES }
